# Query
query Authenticate($token: String!) {
    authenticate(token: $token) {
        ...UserFragment
    }
}

# Mutation
mutation Signup($email: String!, $password: String!, $name: String!) {
    signup(email: $email, password: $password, name: $name) {
        ...AuthPayloadFragment
    }
}

mutation Login($email: String!, $password: String!) {
    login(email: $email, password: $password) {
        ...AuthPayloadFragment
    }
}

# Fragment
fragment AuthPayloadFragment on AuthPayload {
    token
    user {
        ...UserFragment
    }
}

fragment UserFragment on User {
    id
    name
    email
    bio
    posts {
        ...PostFragment
    }
    votes {
        ...VoteFragment
    }
}
