# Query
query Users {
    users {
        ...UserFragment
    }
}

query User($id: ID!) {
    user(id: $id) {
        ...UserFragment
    }
}

# Mutation
mutation UpdateUser($id: ID!, $name: String, $email: String, $bio: String) {
    updateUser(id: $id, name: $name, email: $email, bio: $bio) {
        ...UserFragment
    }
}
