# Query
query Feed($filter: String, $skip: Int, $take: Int, $orderBy: OrderByInput) {
    feed(filter: $filter, skip: $skip, take: $take, orderBy: $orderBy) {
        count
        posts {
            ...PostFragment
        }
    }
}

# Mutation
mutation CreatePost($description: String!, $url: String!) {
    createPost(description: $description, url: $url) {
        ...PostFragment
    }
}

mutation Vote($postId: ID!) {
    vote(postId: $postId) {
        ...VoteFragment
    }
}

mutation Unvote($postId: ID!) {
    unVote(postId: $postId) {
        ...VoteFragment
    }
}

# Subscription
subscription PostCreated {
    postCreated {
        ...PostFragment
    }
}

subscription PostVoted {
    postVoted {
        id
        post {
            ...PostFragment
        }
        user {
            id
        }
    }
}

# Fragment
fragment PostFragment on Post {
    id
    url
    description
    createdAt
    isVotedByMe
    postedBy {
        id
        name
    }
    votes {
        id
        user {
            id
        }
    }
}

fragment VoteFragment on Vote {
    id
    post {
        ...PostFragment
    }
    user {
        id
    }
}
